export const Data3 = [
  {
    id: 1,
    soal: "apabila asisten kapten dalam sebuah tim olahraga meninggal,siapa yangakan memimpintim tersebut nantinya? ",
    jawaban: "kapten",
    jawaban2: "sikapten",
    type: 2,
    point: 8,
  },
  {
    id: 2,
    soal: "kata sonsisten di artikan sebagai?",
    jawaban: "hukumdaras",
    jawaban2: "hukumdasartertingginyangmembuathalhalmengenaipenyelenggeraannegara",
    type: 1,
    point: 6,
  },
  {
    id: 3,
    soal: "buah apa yang paling kaya?",
    jawaban: "buahsrikaya",
    jawaban2: "srikaya",
    type: 2,
    point: 8,
  },
  {
    id: 4,
    soal: "apa sila ke empat dari panca sila?",
    jawaban:
      "kerakyatanyangdipimpinolehhikmatkebijaksanaandalampermusyawaratanperwakilan",
    jawaban2:
      "kerakyatanyangdipimpinolehhikmatkebijaksanaandalampermusyawaratanperwakilan",
    type: 1,
    point: 6,
  },
  {
    id: 5,
    soal: "kalo sedang sendiri,kakinya ada empat kalo sedang berdua kakinya ada delapan siapakan aku??",
    jawaban: "kursi",
    jawaban2: "kursi",
    type: 2,
    point: 8,
  },
  {
    id: 6,
    soal: "sebutkan ibu kota jawabarat?",
    jawaban: "bandung",
    jawaban2: "kotabandung",
    type: 1,
    point: 6,
  },
  {
    id: 7,
    soal: "tentara apa yang ukurannya kecil kecil?",
    jawaban: "tentarasekutu",
    jawaban2: "tentarasekutu",
    type: 2,
    point: 8,
  },
  {
    id: 8,
    soal: "siapakah presiden ke dua di indonesia?",
    jawaban: "suharto",
    jawaban2: "bapaksuharto",
    type: 1,
    point: 6,
  },
  {
    id: 9,
    soal: "apa yang memiliki 12 kaki dan bisa terbang?",
    jawaban: "6ekorburung",
    jawaban2: "enamekorburung",
    type: 2,
    point: 8,
  },
  {
    id: 10,
    soal: "aku selalu ada di atas ustad dan juga presiden tapi aku tidak punya jabatan apapun dalam pemerintakan siapakah aku?",
    jawaban: "peci",
    jawaban2: "peci",
    type: 2,
    point: 8,
  },
  {
    id: 11,
    soal: "saat di balik akan berkembang 3 apakah itu?",
    jawaban: "angka9",
    jawaban2: "angkasembilan",
    type: 2,
    point: 8,
  },
  {
    id: 12,
    soal: "ayam ayam apa yang paling besar?",
    jawaban: "ayamsemesta",
    jawaban2: "ayamsemesta",
    type: 2,
    point: 8,
  },
  {
    id: 13,
    soal: "kebo apa yang bikin lelah?",
    jawaban: "kebogorjalankaki",
    jawaban2: "kebogorjalankaki",
    type: 2,
    point: 8,
  },
  {
    id: 14,
    soal: "apa nama sebuah benda yang kalo di tutup berubah menjadi tongkat tapi ketika di buka jadi sebuah tenda?",
    jawaban: "payung",
    jawaban2: "payung",
    type: 2,
    point: 8,
  },
  {
    id: 15,
    soal: "hewan apa yang bersaudara?",
    jawaban: "katakberadik",
    jawaban2: "katakberadik",
    type: 2,
    point: 8,
  },
];
