export const Data1 = [
  {
    id: 1,
    soal: "Apa nama benua terluas di dunia?",
    jawaban: "asia",
    jawaban2: "benuaasia",
    type: 1,
    point: 6,
  },
  {
    id: 2,
    soal: "erik mempunyai 2 anak, dan istrinya mempunyai 2 anak berapa jumlah anak mereka ?",
    jawaban: "2",
    jawaban2: "dua",
    type: 2,
    point: 8,
  },
  {
    id: 3,
    soal: "Orang apa yang rajin renang, tapi rambutnya nggak pernah basah?",
    jawaban: "botak",
    jawaban2: "orangbotak",
    type: 2,
    point: 8,
  },
  {
    id: 4,
    soal: "SEA Games diadakan setiap berapa tahun sekali?....tahun",
    jawaban: "2",
    jawaban2: "dua",
    type: 1,
    point: 6,
  },
  {
    id: 5,
    soal: "Benda kecil apa yang bisa ngeluarin orang? ",
    jawaban: "bel",
    jawaban2: "belrumah",
    type: 2,
    point: 8,
  },
  {
    id: 6,
    soal: "negara manakah yang memiliki wilayah terluas di dunia? ",
    jawaban: "rusia",
    jawaban2: "negararusia",
    type: 1,
    point: 6,
  },
  {
    id: 7,
    soal: "Sepatu, sepatu apa yang bisa di pakai masak?",
    jawaban: "spatula",
    jawaban2: "sepatula",
    type: 2,
    point: 8,
  },
  {
    id: 8,
    soal: "Jumlah propinsi di Indonesia? .... provinsi",
    jawaban: "38",
    jawaban2: "tigapuluhdelapan",
    type: 1,
    point: 6,
  },
  {
    id: 9,
    soal: "Lemari apa yang bisa masuk ke dalam saku?",
    jawaban: "lemaribuan",
    jawaban2: "limaribuan",
    type: 2,
    point: 8,
  },
  {
    id: 10,
    soal: "Nama kerajaan Islam pertama di Indonesia?",
    jawaban: "pasai",
    jawaban2: "samuderapasai",
    type: 1,
    point: 6,
  },
  {
    id: 11,
    soal: ".Ditembak ke bawah, tapi malah hidung yang kena. Apakah itu?",
    jawaban: "kentut",
    jawaban2: "kentut",
    type: 2,
    point: 8,
  },
  {
    id: 12,
    soal: "Di manakah kantor PBB?",
    jawaban: "newyork",
    jawaban2: "kotanewyork",
    type: 1,
    point: 6,
  },
  {
    id: 13,
    soal: "Kapankah waktu yang tepat untuk membuka pintu?",
    jawaban: "saatpintumasihtertutup",
    jawaban2: "saatpintutertutup",
    type: 2,
    point: 8,
  },
  {
    id: 14,
    soal: "Peristiwa berputarnya bumi mengelilingi matahari.",
    jawaban: "revolusibumi",
    jawaban2: "revolusibumi",
    type: 1,
    point: 6,
  },
  {
    id: 15,
    soal: "Apa sesuatu yang selalu ingin dijawab tapi nggak punya pertanyaan?",
    jawaban: "telpon",
    jawaban2: "telepon",
    type: 2,
    point: 8,
  },
];

// type = 1 "pengetahuan umum"
// type = 2 "teka teki"
// type = 3 "inggris"
