export const Data2 = [
  {
    id: 1,
    soal: "Patung Sphinx kebanyakan terdapat di negara",
    jawaban: "mesir",
    jawaban2: "negaramesir",
    type: 1,
    point: 6,
  },
  {
    id: 2,
    soal: "Bahan bakar kereta api adalah",
    jawaban: "batubara",
    jawaban2: "bara",
    type: 1,
    point: 6,
  },
  {
    id: 3,
    soal: "Kalau ada angsa lima, dikali dua. Berapa total semua angsa?",
    jawaban: "5",
    jawaban2: "lima",
    type: 2,
    point: 8,
  },
  {
    id: 4,
    soal: "Kapan Hari Sumpah Pemuda diperingati",
    jawaban: "28oktober",
    jawaban2: "28-10",
    type: 1,
    point: 6,
  },
  {
    id: 5,
    soal: "Apa alat musik tradisional Nusa Tenggara Timur",
    jawaban: "sasando",
    jawaban2: "sasando",
    type: 1,
    point: 6,
  },
  {
    id: 6,
    soal: "apa yang ada di ujung langit",
    jawaban: "t",
    jawaban2: "huruft",
    type: 2,
    point: 8,
  },
  {
    id: 7,
    soal: "apa rumah adat provinsi jawa barat",
    jawaban: "panggung",
    jawaban2: "rumahpanggung",
    type: 1,
    point: 6,
  },
  {
    id: 8,
    soal: "siapakah penemu mesin uap",
    jawaban: "jameswat",
    jawaban2: "jameswatt",
    type: 1,
    point: 6,
  },
  {
    id: 9,
    soal: "sungai terpanjang di dunia adalah?",
    jawaban: "nil",
    jawaban2: "sungainil",
    type: 1,
    point: 6,
  },
  {
    id: 10,
    soal: "apakah huruf keempat dari abjad",
    jawaban: "a",
    jawaban2: "hurufa",
    type: 2,
    point: 8,
  },
  {
    id: 11,
    soal: "tahun berapa manusia pertama kali menginjakan di bulan?",
    jawaban: "1969",
    jawaban2: "seribusembilanratusenampuluhsembilan",
    type: 1,
    point: 6,
  },
  {
    id: 12,
    soal: "kantor pbb terletak di kota?",
    jawaban: "newyork",
    jawaban2: "kotanewyork",
    type: 1,
    point: 6,
  },
  {
    id: 13,
    soal: "siapakah penemu radio?",
    jawaban: "marconi",
    jawaban2: "marconi",
    type: 1,
    point: 6,
  },
  {
    id: 14,
    soal: "apa kepanjangan dari DPD?",
    jawaban: "dewanperwakilandaerah",
    jawaban2: "dewanperwakilandaerah",
    type: 1,
    point: 6,
  },
  {
    id: 15,
    soal: "apa ibu kota jawa barat",
    jawaban: "bandung",
    jawaban2: "kotabandung",
    type: 1,
    point: 6,
  },
];
